### ISSUE TITLE
Create a “logo”

### ISSUE THREAD

**Issue by FarazzShaikh** [Andrew-Colman/sync-fork#26]
We should create an ASCII art logo something like this
![image](https://user-images.githubusercontent.com/55190601/105863801-48649e00-6017-11eb-885c-1a33956249bb.jpeg)

Can be easily make using [this tool.](https://www.patorjk.com/software/taag/#p=display&f=Graffiti&t=Type%20Something%20)

**Comment by Andrew-Colman** [comment]
current logo:
```rb
§
```

_it's the paragraph sign lol_

reminds of a reload icon with an S

↻

I think 🤣
